server:
  port: 8761

spring:
  output:
    ansi:
      enabled: always
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false