apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: hwijae/biday-config-server:1.0
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: ssh-key
              mountPath: /var/lib/jenkins/.ssh/id_rsa
              subPath: id_rsa

          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "git@github.com:biday5/biday-secret.git"
      volumes:
        - name: ssh-key
          secret:
            secretName: git-ssh-key
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server
