apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-service
  template:
    metadata:
      labels:
        app: ftp-service
    spec:
      containers:
        - name: ftp-service
          image: hwijae/biday-ftp-service:1.0
          ports:
            - containerPort: 9102
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
spec:
  type: ClusterIP
  ports:
    - port: 9102
      targetPort: 9102
  selector:
    app: ftp-service
