services:
  eureka-server:
    image: hwijae/biday-eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - biday-network
    depends_on:
      - config-server
    hostname: biday-eureka-host

  config-server:
    image: hwijae/biday-config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - biday-network
    hostname: biday-config-host

  gateway-server:
    image: hwijae/biday-gateway-server:1.0
    container_name: gateway-server
    ports:
      - "8000:8000"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-gateway-host

  admin-service:
    image: hwijae/biday-admin-service:1.0
    container_name: admin-service
    ports:
      - "9100:9100"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-admin-host

  auction-service:
    image: hwijae/biday-auction-service:1.0
    container_name: auction-service
    ports:
      - "9101:9101"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-auction-host

  ftp-service:
    image: hwijae/biday-ftp-service:1.0
    container_name: ftp-service
    ports:
      - "9102:9102"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-ftp-host

  order-service:
    image: hwijae/biday-order-service:1.0
    container_name: order-service
    ports:
      - "9103:9103"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-order-host

  product-service:
    image: hwijae/biday-product-service:1.0
    container_name: product-service
    ports:
      - "9104:9104"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-product-host

  user-service:
    image: hwijae/biday-user-service:1.0
    container_name: user-service
    ports:
      - "9106:9106"
    networks:
      - biday-network
    depends_on:
      - config-server
      - eureka-server
    hostname: biday-user-host

networks:
  biday-network:
    external: true