version: '3.0'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/demo/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/demo/var/lib/mysql:/var/lib/mysql
      - ./mysql/demo/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=bidaydb
      - MYSQL_ROOT_PASSWORD=biday
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always
    networks:
      - biday-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass biday
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    networks:
      - biday-network

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/mydb
      - ./mongodb/conf/mongod.conf:/etc/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=biday
      - MONGO_INITDB_DATABASE=bidaydb
    restart: always
    networks:
      - biday-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/biday/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/biday/nginx/cert:/etc/nginx/cert
      - /home/biday/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - biday-network

networks:
  biday-network:
    external: true