pipeline {
    agent any

    environment {
        DOCKER_HUB_URL = "${docker_hub_url}"
        DOCKER_HUB_CREDENTIAL = credentials('dockerhub')
    }

    tools {
        gradle 'gradle_8.10'
    }

    stages {
        stage('Check for Changes') {
            steps {
                script {
                    // 현재 커밋 해시 가져오기
                    def currentCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
                    echo "currentCommit: ${currentCommit}"

                    // 이전 빌드의 커밋 해시 가져오기 (없으면 빈 문자열)
                    def previousCommit = sh(script: 'git rev-parse HEAD~1 || echo ""', returnStdout: true).trim()
                    echo "previousCommit: ${previousCommit}"

                    def changes = sh(script: "git diff --name-only ${previousCommit} ${currentCommit}", returnStdout: true).trim()
                    echo "changes: ${changes}"
                    if (changes) {
                        echo '변동사항이 있습니다.'
                        echo "변경된 파일들: ${changes}"
                    } else {
                        echo '변동사항이 없습니다.'
                        currentBuild.result = 'ABORTED'
                        error '변동 사항이 없으므로 파이프라인을 중단합니다.'
                    }
                }
            }
        }

        stage('Gradle Build') {
            steps {
                echo '=== build modules shell script start ==='
                sh './buildModule.sh'
            }
        }

        stage('Docker Image Build and Push') {
            steps {
                script {
                    echo "docker_hub_url >>>>>>> ${docker_hub_url}"
                    echo "BUILD_TAG >>>>>> ${BUILD_TAG}"
                    def allModules = [
                        "server:eureka-server",
                        "server:config-server",
                        "server:gateway-server",
                        "service:admin-service",
                        "service:auction-service",
                        "service:ftp-service",
                        "service:order-service",
                        "service:product-service",
                        "service:sms-service",
                        "service:user-service"
                    ]                    

                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIAL) {
                        for (module in allModules) {
                            def repoName = "${DOCKER_HUB_URL}/biday-${module.split(':')[1]}"
                            echo "Building and pushing ${repoName}..."

                            def image = docker.build(repoName, "${module}:${BUILD_TAG}")

                            image.push()
                        }
                    }
                }
            }
        }
    }
    
    post{
        success{
            echo "========pipeline executed successfully ========"
            echo "Image 정리..."
        }
        failure{
            echo "========pipeline execution failed========"
        }
        always{
            echo 'Workspace 정리..'
        }
    }
}