server:
  port: 9103

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  output:
    ansi:
      enabled: always
  application:
    name: order-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888/

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
      time-zone: UTC

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bidaydb
    username: root
    password: biday

  data:
    redis:
      host: redis
      port: 6379
      password: biday
      repositories:
        enabled: false

openapi:
  service:
    url: http://localhost:8000
  swagger-ui:
    path: /swagger-ui

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/payments/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

payments:
  toss:
    secret:
      key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6