server:
  port: 9102

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://biday-eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  output:
    ansi:
      enabled: always
  application:
    name: ftp-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  data:
    mongodb:
      username: root
      password: biday
      host: localhost
      port: 27017
      database: bidaydb
      authentication-database: admin

  s3:
    accessKey: B93C5A01D2C3EDEFDA4D
    secretKey: AAC1613AE24201F432707E7F73618CE0E9476766
    bucket: biday