spring:
  output:
    ansi:
      enabled: always
  application:
    name: ftp-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config-server:8888/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB